### ISSUE TITLE
Forge Not initializing correctly

### ISSUE THREAD

**Issue by TheRoar02** [Cat5TV/pinecraft#29]
After instillation using Pinecraft 2.9  and selecting forge 1.16.5. I have tried on clean instillations of the recommended os, ubuntu server 21.04, and ubuntu server 20.02.04 LTS. On both I receive a warning: "Forge appears to have installed, but is not initializing correctly. It is unlikely to work until this is resolved." 
<img width="1227" alt="Screen Shot 2021-08-16 at 9 49 09 PM" src="https://user-images.githubusercontent.com/15306162/129665740-8e036057-ee02-43c4-92c9-331d7405266b.png"> 
Then this is the dialog I see after trying to run the server:

```
Installation complete.

Minecraft server is now running on 10.10.0.51

Remember: World generation can take a few minutes. Be patient.

Documentation: https://github.com/Cat5TV/Pinecraft

Support The Project: https://patreon.com/Pinecraft

ubuntu@ubuntu:$ ./minecraft/server 
[04:49:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.1.0, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --nogui]
[04:49:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 16.0.1 by Private Build
Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x4434095f) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x4434095f
        at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
        at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)
        at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
        at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
        at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
        at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
1 ubuntu@ubuntu:~$ 


```

**Comment by NodeNextOfficial** [comment]
Ubuntu Server 21.04 64-Bit Is recommend for the base OS
https://github.com/Cat5TV/pinecraft#base-os

**Comment by Cat5TV** [comment]
I believe this has been fixed with the release of Pinecraft Installer 3.1. The Forge developers made changes to their own installer which broke the integration with Pinecraft Installer. I've since re-engineered the installer and integrated the changes.

**Comment by TheRoar02** [comment]
Currently testing 3.1 to install fabric and forge servers and having no issues. Thanks for all the work you do, Robbie!

**Comment by Cat5TV** [comment]
Awesome, thanks for the update @TheRoar02 - ENJOY!

**Comment by ThorinHanson** [comment]
Getting the same error with 3.1 on Ubuntu 21.10.
